### ISSUE TITLE
Collect data for multiple repos at once

### ISSUE THREAD

**Issue by zeke** [nice-registry/cool-story-repo#7]
@gr2m once said:

> First thing I would do is to send a single request instead of one per repository. You can do that using query aliases: http://graphql.org/learn/queries/#aliases

We could update this module to optionally take an array of repo names instead of just one:

```js
const repoNames = ['zeit/hyper', 'electron/electron']
const repos = await coolStory(repoNames)
```

**Comment by echjordan** [comment]
@zeke Its possible to run the same subquery multiple times if each is aliased with a different name. I want to try and  implement by mapping through each repo, using string interpolation and 'i' value to generate an alias name for each repo's query, package into one query _then_ make single request to the client

**Comment by zeke** [comment]
@echjordan landed this in https://github.com/nice-registry/cool-story-repo/pull/12 🎉
